---
- name: Build container image
  docker_image:
    name: nginx_test
    path: "."
    state: present

- name: Create default containers
  docker_container:
    name: nginx_test
    image: nginx_test
    state: present
    exposed_ports:
      - "80:80"