---
- name: Build container image
  docker_image:
    name: nginx_test
    build:
      path: "."
    source: build
    pull: no
    state: present

- name: Create default containers
  docker_container:
    name: nginx_test
    image: nginx_test
    state: started
    exposed_ports:
      - "80:80"