---
- name: Delete nginx container if presented
  docker_container:
    name: nginx_test
    state: absent

- name: Build container image
  docker_image:
    name: nginx_test
    build:
      path: "."
      pull: no
    source: build
    state: present

- name: Create default containers
  docker_container:
    name: nginx_test
    image: nginx_test
    state: started
    exposed_ports:
      - "80:80"