---
- name: Uninstall Previous Docker packages Ubuntu
  apt:
    pkg: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

- name: Add Docker Repository Ubuntu
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install docker Ubuntu
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io


