name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        
    - name: Forming TAG
      run: echo "::set-output name=tag_sha::$(curl -u didistars328:${{ secrets.TEST_TAG_SECRET }} https://api.github.com/repos/didistars328/test-task/git/refs/heads/master | jq -r '.object.sha' | head -c 7)"

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.TEST_TAG_SECRET }}
        WITH_V: false
        CUSTOM_TAG: oss_version_${{ steps.forming-tag.outputs.tag_sha }}
