---
- name: Uninstall Previous Docker packages Ubuntu
  apt:
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
- name: Detect Ubuntu release
  shell: lsb_release -cs
  register: release

- debug: var=release

- name: Run apt upgrade
  apt:
    upgrade: "yes"
    update_cache: yes

- name: Add key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository Ubuntu
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ release.stdout }} stable
    state: present
    update_cache: true

- name: Install docker Ubuntu
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io


